name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: set -o pipefail && xcodebuild clean test -scheme Iron -project Iron.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11' | xcpretty
