name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app

    - name: Test
      run: xcodebuild clean test -scheme Iron -project Iron.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11'
